FileVersion = 1
Projects = {beef-maker-engine = {Path = "engine"}, GLFW = {Path = "vendor/glfw-beef"}, ImGuiImplGlfw = {Path = "vendor/imgui-beef/ImGuiImplGlfw"}, ImGui = {Path = "vendor/imgui-beef/ImGui"}, ImGuiImplOpenGL3 = {Path = "vendor/imgui-beef/ImGuiImplOpenGL3"}, beef-maker-editor = {Path = "editor"}}
Locked = ["GLFW", "ImGuiImplGlfw", "ImGui", "ImGuiImplOpenGL3"]
WorkspaceFolders = {Dependencies = ["corlib", "GLFW", "ImGui", "ImGuiImplGlfw", "ImGuiImplOpenGL3"], BeefMaker = ["beef-maker-engine", "beef-maker-editor"]}

[Workspace]
StartupProject = "beef-maker-editor"
